Unicode awesomeness for PS1

diff --git a/dotfiles/.bashrc.d/ps1 b/dotfiles/.bashrc.d/ps1
--- a/dotfiles/.bashrc.d/ps1
+++ b/dotfiles/.bashrc.d/ps1
@@ -1,23 +1,5 @@
 #!/usr/bin/env bash
 function setup_ps1 {
-    function parse_login_shell {
-        shopt -q login_shell && echo '(login_shell)'
-    }
-    function parse_status {
-        if [[ $? != 0 ]]; then
-            echo "-=(error)=-"
-        fi
-    }
-    function parse_git_branch {
-        git branch --no-color 2> /dev/null \
-            | sed -e '/^[^*]/d' -e 's/* \(.*\)/\[\1\]/'
-    }
-    function parse_ruby_version {
-        regexp="([0-9]\.[0-9](\.[0-9])?)"
-        [[ `ruby --version` =~ $regexp ]]
-        echo "${BASH_REMATCH[1]}"
-    }
-
     # Colors
     local txtblk='\[\e[0;30m\]' # Black - Regular
     local txtred='\[\e[0;31m\]' # Red
@@ -43,85 +25,116 @@ function setup_ps1 {
     local undpur='\[\e[4;35m\]' # Purple
     local undcyn='\[\e[4;36m\]' # Cyan
     local undwht='\[\e[4;37m\]' # White
-    local bakblk='\[\e[40m\]'   # Black - Background
-    local bakred='\[\e[41m\]'   # Red
-    local bakgrn='\[\e[42m\]'   # Green
-    local bakylw='\[\e[43m\]'   # Yellow
-    local bakblu='\[\e[44m\]'   # Blue
-    local bakpur='\[\e[45m\]'   # Purple
-    local bakcyn='\[\e[46m\]'   # Cyan
-    local bakwht='\[\e[47m\]'   # White
-    local hiblk='\[\e[0;90m\]'  # Black - High intensity
-    local hired='\[\e[0;91m\]'  # Red
-    local higrn='\[\e[0;92m\]'  # Green
-    local hiylw='\[\e[0;93m\]'  # Yellow
-    local hiblu='\[\e[0;94m\]'  # Blue
-    local hipur='\[\e[0;95m\]'  # Purple
-    local hicyn='\[\e[0;96m\]'  # Cyan
-    local hiwht='\[\e[0;97m\]'  # White
-    local clroff='\[\e[0m\]'    # Text Reset
+    local bakblk='\[\e[40m\]' # Black - Background
+    local bakred='\[\e[41m\]' # Red
+    local bakgrn='\[\e[42m\]' # Green
+    local bakylw='\[\e[43m\]' # Yellow
+    local bakblu='\[\e[44m\]' # Blue
+    local bakpur='\[\e[45m\]' # Purple
+    local bakcyn='\[\e[46m\]' # Cyan
+    local bakwht='\[\e[47m\]' # White
+    local hiblk='\[\e[0;90m\]' # Black - High intensity
+    local hired='\[\e[0;91m\]' # Red
+    local higrn='\[\e[0;92m\]' # Green
+    local hiylw='\[\e[0;93m\]' # Yellow
+    local hiblu='\[\e[0;94m\]' # Blue
+    local hipur='\[\e[0;95m\]' # Purple
+    local hicyn='\[\e[0;96m\]' # Cyan
+    local hiwht='\[\e[0;97m\]' # White
+    local clroff='\[\e[0m\]' # Text Reset
 
     # other variables with human readable names
-    # \a          an ASCII bell character (07)
-    # \d          the date in "Weekday Month Date" format (e.g., "Tue May 26")
-    # \D{format}  the format is passed to strftime(3) and the result
-    #             is inserted into the prompt string an empty format
-    #             results in a locale-specific time representation.
-    #             The braces are required
-    # \e          an ASCII escape character (033)
-    # \h          the hostname up to the first `.'
-    # \H          the hostname
-    # \j          the number of jobs currently managed by the shell
-    # \l          the basename of the shell's terminal device name
-    # \n          newline
-    # \r          carriage return
-    # \s          the name of the shell, the basename of $0 (the portion following
-    #             the final slash)
-    # \t          the current time in 24-hour HH:MM:SS format
-    # \T          the current time in 12-hour HH:MM:SS format
-    # \@          the current time in 12-hour am/pm format
-    # \A          the current time in 24-hour HH:MM format
-    # \u          the username of the current user
-    # \v          the version of bash (e.g., 2.00)
-    # \V          the release of bash, version + patch level (e.g., 2.00.0)
-    # \w          the current working directory, with $HOME abbreviated with a tilde
-    # \W          the basename of the current working directory, with $HOME
-    #             abbreviated with a tilde
-    # \!          the history number of this command
-    # \#          the command number of this command
-    # \$          if the effective UID is 0, a #, otherwise a $
-    # \nnn        the character corresponding to the octal number nnn
-    # \\          a backslash
-    # \[          begin a sequence of non-printing characters, which could be used
-    #             to embed a terminal control sequence into the prompt
-    # \]          end a sequence of non-printing characters
+    # \a an ASCII bell character (07)
+    # \d the date in "Weekday Month Date" format (e.g., "Tue May 26")
+    # \D{format} the format is passed to strftime(3) and the result
+    # is inserted into the prompt string an empty format
+    # results in a locale-specific time representation.
+    # The braces are required
+    # \e an ASCII escape character (033)
+    # \h the hostname up to the first `.'
+    # \H the hostname
+    # \j the number of jobs currently managed by the shell
+    # \l the basename of the shell's terminal device name
+    # \n newline
+    # \r carriage return
+    # \s the name of the shell, the basename of $0 (the portion following
+    # the final slash)
+    # \t the current time in 24-hour HH:MM:SS format
+    # \T the current time in 12-hour HH:MM:SS format
+    # \@ the current time in 12-hour am/pm format
+    # \A the current time in 24-hour HH:MM format
+    # \u the username of the current user
+    # \v the version of bash (e.g., 2.00)
+    # \V the release of bash, version + patch level (e.g., 2.00.0)
+    # \w the current working directory, with $HOME abbreviated with a tilde
+    # \W the basename of the current working directory, with $HOME
+    # abbreviated with a tilde
+    # \! the history number of this command
+    # \# the command number of this command
+    # \$ if the effective UID is 0, a #, otherwise a $
+    # \nnn the character corresponding to the octal number nnn
+    # \\ a backslash
+    # \[ begin a sequence of non-printing characters, which could be used
+    # to embed a terminal control sequence into the prompt
+    # \] end a sequence of non-printing characters
 
-    time24h="\A"
-    path="\w"
-    newline="\n"
-    jobs="\j"
-    user="\u"
-    host="\H"
+    local time24h="\A"
+    local path="\w"
+    local newline="\n"
+    local user="\u"
+    local host="\h"
 
-    # building PS1 out of various parts
+    dotsep=" ⋅ "
+    local whtdot="$bldwht$dotsep$clroff"
+
+    function parse_login_shell {
+	shopt -q login_shell && echo '(login) '
+    }
+    function parse_status {
+	if [[ $? != 0 ]]; then
+	    echo "-=(error)=-"
+	fi
+    }
+
+    function format_git_branch {
+	local branch="$(git branch --no-color 2> /dev/null | \
+ sed -e '/^[^*]/d' -e 's/* \(.*\)/\1/')"
+
+	if [ -n "$branch" ]; then
+	    printf "$dotsep⺦($branch)"
+	fi
+    }
+
+    function format_ruby_version {
+	regexp="([0-9]\.[0-9](\.[0-9])?)"
+	[[ `ruby --version` =~ $regexp ]]
+	version="${BASH_REMATCH[1]}"
+
+	if [ -n "$version" ]; then
+	    printf "$dotsep𝛅($version) "
+	fi
+    }
+
+    local curtime="$hicyn$time24h$whtdot"
+    local user_at_host="$hiblu𝛴($user$txtred@$hiblu$host)$whtdot"
+    local status="$hired\$(parse_status)"
+    local path="$txtcyn𝛹 ($path)"
+    local git_branch="$txtgrn\$(format_git_branch)"
+    local login_shell_indicator="$hiblu\$(parse_login_shell)"
+    local ruby_version="$txtred\$(format_ruby_version)"
+    local final="$bldbluλx ➝  "
+
     PS1=""
 
-    #time part
-    PS1+="$hicyn[$time24h]$clroff"
-    #status part
-    PS1+="$hired\$(parse_status)$clroff"
-    #git branch part
-    PS1+="$bldred\$(parse_git_branch)$clroff"
-    #ruby version part
-    PS1+="$undblu{$hiblu\$(parse_ruby_version)$undblu}$clroff"
-    #path part
-    PS1+="$clroff[$txtcyn$path$clroff]"
-    #line break
-    PS1+="$newline"
-    #login shell indicator part
-    PS1+="$hiblu\$(parse_login_shell)"
-    #user and hostname part
-    PS1+="$hipur$user$txtred@$hiwht$host$clroff"
-    #final part
-    PS1+="$txtwht(\#)$clroff-> "
+    PS1+=$curtime
+    PS1+=$status
+    PS1+=$user_at_host
+    PS1+=$path
+    PS1+=$git_branch
+    PS1+=$ruby_version
+    PS1+=$newline
+    PS1+=$login_shell_indicator
+    PS1+=$final
+
+    PS1+=$clroff
 }
